# Generated by Django 5.1.2 on 2024-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_valuation_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsearch',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
