# Generated by Django 5.1.2 on 2024-10-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='offer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
