# Generated by Django 5.1.2 on 2024-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='data_period',
            field=models.DateField(unique=True),
        ),
    ]
