# Generated by Django 5.1.2 on 2024-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingjob_data_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_period', models.DateField(unique=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('correlation_file', models.FileField(blank=True, null=True, upload_to='correlations/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='scalers/')),
                ('columns_file', models.FileField(blank=True, null=True, upload_to='columns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed_import', 'Failed DB import'), ('failed_training', 'Failed model Training')], default='pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingJob',
        ),
    ]
