# Generated by Django 5.1.2 on 2024-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_valuationmodel_delete_trainingjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuationmodel',
            name='columns_file',
        ),
        migrations.RemoveField(
            model_name='valuationmodel',
            name='correlation_file',
        ),
        migrations.RemoveField(
            model_name='valuationmodel',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='valuationmodel',
            name='scaler_file',
        ),
        migrations.AddField(
            model_name='valuationmodel',
            name='columns_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuationmodel',
            name='correlation_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuationmodel',
            name='model_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valuationmodel',
            name='scaler_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
